name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [release]
        include:
          - os: ubuntu-latest
            cpp_compiler: clang17

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install dependencies
      shell: bash
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install ninja
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install ninja
        fi      
    - name: configure
      run: make configure PRESET=${{ matrix.cpp_compiler }}-${{ matrix.build_type }}
    - name: build
      run: make build PRESET=${{ matrix.cpp_compiler }}-${{ matrix.build_type }}
    - name: test
      run: make test PRESET=${{ matrix.cpp_compiler }}-${{ matrix.build_type }}

